name: 签到

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 22,14 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2
      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: 签到
        run: |
          pip install -r requirements.txt

          user='${{ secrets.USER }}'
          pwd='${{ secrets.PWD }}'
          sckey='${{ secrets.SCKEY }}'
          python3 checkin.py <<EOF
          ${user}
          ${pwd}
          ${sckey}
          EOF
